package ca.nines.ise.constants;

public class XML {
	  public static final String[] ALIGNMENT ={"right","center","justify"};
	  public static final String QLN = "qln";
	  public static final String WLN = "wln";
	  public static final String TLN = "tln";
	  public static final String LINK = "link";
	  public static final String META = "meta";
	  public static final String RULE = "rule";
	  public static final String SPACE = "space";
	  public static final String BR = "br";
	  public static final String COL = "col";
	  public static final String ISEHEADER = "iseheader";
	  public static final String SP = "sp";
	  public static final String LINEGROUP = "linegroup";
	  public static final String MARG = "marg";
	  public static final String TITLE = "title";
	  public static final String QUOTE = "quote";
	  public static final String WORK = "work";
	  public static final String PAGE = "page";
	  public static final String LINE = "l";
	  public static final String RA = "ra";
	  public static final String C = "c";
	  public static final String J = "j";
	  public static final String S = "s";
	  public static final String Q = "q";
	  public static final String MS = "ms";
	  public static final String ACT = "act";
	  public static final String SCENE = "scene";
	  public static final String MODE = "mode";
	  public static final String AMBIG = "ambig";
	  public static final String RDG = "rdg";
	  public static final String PROP = "prop";
	  public static final String SD = "sd";
	  public static final String RT = "rt";
	  public static final String PN = "pn";
	  public static final String SIG = "sig";
	  public static final String CW = "cw";	  
}
